### ISSUE TITLE
Make `message.value` a `Nullable!Pattern` ?

### ISSUE THREAD

**Issue by Pike** [SirNickolas/fluentd#2]
In the existing Fluent API, the `value` on Message is optional. AFAICT, that's represented as an empty pattern right now? Would `Nullable!Pattern` work?

Note, I know nothing about D aside from looking that one thing up on google, so take that with a grain or a bag of salt.

**Comment by SirNickolas** [comment]
Yes, it’s represented as an empty pattern now. The reason for a change is that APIs in all languages should be as consistent as possible?

`Nullable` is indeed a standard library citizen, but, in my opinion, it has a fundamental flaw: `Nullable!T` **implicitly** converts to `T`, `assert`ing at runtime (in debug builds) if it is `null`. So I’d prefer [`SumType!(Nothing, T)`](https://github.com/pbackus/sumtype) instead.
